{% raw %}
website_bucket_stack:
  region: "{{ aws_region }}"
  stack_name: LPEmbeddableApps
  template: '{{ playbook_dir + "/stack/website-bucket.yaml" }}'
  create_changeset: true
  termination_protection: true

  template_parameters:
    WebsiteBucketName: <<FILL IN>>
{% endraw %}